Script started on 2020-12-09 17:40:49-07:00
]0;jeremy.kimotho@csa1:~/Desktop/CPSC_355/project_2jeremy.kimotho@csa1:~/Desktop/CPSC_355/project_2$ exit[2Plsgdb --args project jeremy 10 10[4Pcc project.s -g -o projectdb --args project jeremy 10 10ls[Kexit[K./project jeremy 10 10

*****Program Starts*****

Negative numbers 40/100 = 40 percent
Positive numbers 40/100 = 40 percent
Special tiles 20/100 = 20 percent

-11.14 $ -2.14 $ 13.68 14.36 $ 14.10 $ -13.94 
$ * $ $ $ -11.97 -8.42 $ -2.04 -14.42 
-14.81 -9.30 $ $ -0.97 -4.71 8.68 -10.04 $ $ 
$ 13.17 -3.30 -10.01 $ -1.90 -0.14 $ $ 14.90 
-11.36 -3.87 12.78 -12.62 -0.49 -2.42 -2.39 -6.07 -8.07 2.07 
$ -4.01 -10.42 -4.71 -11.42 $ -11.52 -4.14 -5.49 -11.71 
-6.97 $ -13.14 4.01 13.94 -10.10 -12.84 -11.71 12.65 # 
-12.20 4.84 -9.04 1.04 12.71 8.52 13.87 13.97 4.10 2.23 
10.07 @ 13.46 0.14 13.01 5.14 3.20 4.00 5.94 3.62 
8.30 2.62 6.17 0.68 1.84 5.20 5.58 14.62 10.68 11.71 

X X X X X X X X X X 
X X X X X X X X X X 
X X X X X X X X X X 
X X X X X X X X X X 
X X X X X X X X X X 
X X X X X X X X X X 
X X X X X X X X X X 
X X X X X X X X X X 
X X X X X X X X X X 
X X X X X X X X X X 
Lives: 3
Score: 0.00
Bombs: 3

Enter bomb position (x,y): 2,5

Total uncovered score of -19.43 points
Your score has dipped below zero, you have lost a life :( 
X X X X X X X X X X 
X X X X $ - - X X X 
X X X X - - + X X X 
X X X X $ - - X X X 
X X X X X X X X X X 
X X X X X X X X X X 
X X X X X X X X X X 
X X X X X X X X X X 
X X X X X X X X X X 
X X X X X X X X X X 
Lives: 2
Score: 0.00
Bombs: 2

Enter bomb position (x,y): 0,0
Bang!! Your bomb range is doubled

Total uncovered score of -49.43 points
Your score has dipped below zero, you have lost a life :( 
- $ - $ + X X X X X 
$ * $ $ $ - - $ X X 
- - $ $ - - + - X X 
$ + - - $ - - $ X X 
- - + - - X X X X X 
X X X X X X X X X X 
X X X X X X X X X X 
X X X X X X X X X X 
X X X X X X X X X X 
X X X X X X X X X X 
Lives: 1
Score: 0.00
Bombs: 1
You have found the exit tile and won the game!

*****Program Ends*****

]0;jeremy.kimotho@csa1:~/Desktop/CPSC_355/project_2jeremy.kimotho@csa1:~/Desktop/CPSC_355/project_2$ 
]0;jeremy.kimotho@csa1:~/Desktop/CPSC_355/project_2jeremy.kimotho@csa1:~/Desktop/CPSC_355/project_2$ ./project jeremy 10 10[K[K[K[K[K50 50

*****Program Starts*****

Negative numbers 1000/2500 = 40 percent
Positive numbers 1000/2500 = 40 percent
Special tiles 500/2500 = 20 percent

-14.14 -10.62 -8.81 -13.52 -13.58 -2.62 -10.58 $ $ -11.30 $ -5.84 $ 3.90 -4.84 $ $ -4.10 -6.52 -12.71 $ $ $ 6.97 -3.84 $ $ $ $ $ -4.71 $ -2.55 $ -11.65 $ $ 5.52 3.42 -11.68 -0.71 1.14 -3.62 0.17 0.30 $ $ -0.68 -12.68 $ 
-11.55 12.58 -9.20 $ $ $ -7.04 -12.30 -9.42 0.14 $ -13.55 8.84 13.26 -13.39 -13.14 -3.17 7.71 -6.87 $ $ -1.04 -1.39 5.10 $ -10.49 $ $ -14.78 7.36 $ $ $ $ -9.20 -3.74 8.42 -11.62 -2.94 $ -2.81 -7.46 -1.42 $ $ $ -13.23 -13.87 $ 6.30 
$ $ -14.26 -3.87 $ -11.10 10.97 -6.39 $ -7.46 $ -7.58 $ -3.17 -14.52 -9.62 $ -5.81 -4.97 $ -1.33 -7.49 -6.01 -11.33 0.04 -8.14 $ 2.90 $ $ -1.55 $ -9.26 -6.20 $ -2.71 -1.23 -13.62 $ -7.84 14.74 -2.68 $ -9.94 -2.49 1.62 $ -1.36 $ -5.04 
$ -10.04 -1.58 -7.23 -2.23 -10.36 6.94 -5.04 10.87 -8.36 -11.39 -13.36 -7.87 -5.00 $ -3.84 -3.33 -11.04 -4.97 8.17 $ $ -2.42 -5.58 -6.81 $ -4.33 $ -14.62 $ 0.81 1.30 $ $ 0.42 $ -8.26 $ -3.58 $ -7.55 $ -8.04 -2.81 $ 11.94 8.55 $ -10.90 $ 
-10.00 -8.87 $ -3.84 -6.84 -4.23 $ -5.94 $ $ -12.97 -10.01 0.74 -1.58 13.01 $ -3.74 -12.26 -12.46 -7.26 $ 1.14 4.94 -0.94 -9.07 -2.62 -10.23 $ $ 8.14 $ 4.42 10.68 -11.52 -3.78 $ $ 8.10 -6.62 -7.33 $ -8.71 -8.58 3.30 $ $ -13.78 $ 2.49 -0.58 
$ 5.30 -12.58 $ -8.39 -5.87 -1.84 $ -7.00 -13.39 $ 3.65 $ $ $ $ -4.39 $ 9.01 $ $ $ -13.58 -0.90 $ $ $ $ -2.39 -0.65 -13.97 3.01 -1.62 $ -13.00 $ $ -14.58 $ $ -0.30 $ -0.30 $ $ $ -13.10 -13.81 -3.68 10.71 
$ 10.42 $ -6.42 -10.71 -3.36 -9.23 1.87 -6.07 12.97 $ 1.65 $ $ -13.71 $ -12.01 14.23 -3.97 $ $ $ -14.01 7.74 5.94 -0.26 8.10 -13.84 -2.33 -4.01 $ $ -9.65 $ -10.87 -2.36 $ -7.97 -6.30 $ -14.30 $ -7.01 $ $ -9.46 $ $ -2.71 $ 
$ $ $ $ -3.71 -6.65 -9.36 6.90 $ $ -4.90 -8.94 $ -13.90 0.81 $ 7.68 $ $ $ -14.07 -8.81 -8.87 $ 14.01 $ $ $ -14.39 -8.46 5.55 -6.52 -5.49 -10.26 $ $ -13.36 2.74 -10.04 -8.71 -2.52 -10.26 -4.71 9.17 9.78 -7.17 $ -11.04 -9.46 -9.81 
$ -11.17 -7.58 $ 12.26 7.52 $ -8.17 1.33 -0.33 $ -1.55 $ $ -9.84 9.62 9.62 -12.00 $ 12.84 $ 13.30 -4.97 $ $ $ -7.52 -1.36 $ -5.94 -6.23 -14.94 2.71 10.87 $ 8.14 0.81 -13.04 -12.71 -7.84 -5.58 $ -4.42 7.94 -10.68 -11.07 $ -5.14 -9.49 $ 
$ $ -13.94 -11.81 -9.30 $ -11.04 $ $ -14.26 -7.14 -10.30 $ -3.97 -3.81 $ 11.33 -11.20 $ -10.65 -7.20 -2.00 -3.65 8.00 $ 0.55 $ -6.55 -4.23 -2.46 -0.52 -5.97 -9.14 $ -14.33 2.78 -11.90 $ -11.97 -2.46 2.39 $ 4.30 $ -14.87 -2.49 -13.23 8.17 -13.68 -4.01 
14.01 * -1.46 $ $ $ -2.74 3.49 -9.71 $ 3.74 -0.78 9.17 -13.26 1.39 9.23 $ 10.74 $ $ -8.30 2.84 # -14.36 -9.26 -14.36 -10.90 -4.81 8.81 -1.87 -7.62 -3.49 -12.71 -11.68 0.10 -14.68 -0.01 -11.20 $ $ $ -8.71 $ -5.10 4.71 -14.14 $ 0.68 10.62 $ 
$ -0.65 -7.01 -6.58 3.68 -9.52 -4.36 -0.42 $ $ 14.52 $ 5.46 $ -2.74 -13.78 -0.01 -10.39 -11.23 -4.74 -4.04 -9.84 1.49 2.04 -1.78 -8.62 $ -13.84 -0.74 -2.10 -4.46 $ -5.90 -11.55 3.23 $ $ -5.00 12.33 -2.26 -0.81 -12.14 $ -9.49 -2.33 6.68 -4.42 -4.71 $ -7.14 
$ $ $ -7.81 $ $ -6.78 -10.46 13.46 8.97 $ -2.84 $ $ $ -11.55 $ 5.42 -4.97 $ -3.10 -4.33 -11.46 5.52 -4.94 4.68 7.81 $ 11.00 -0.36 -11.01 -9.74 $ -13.14 $ $ $ 12.01 $ $ -14.65 -7.55 $ $ -3.87 -3.36 4.36 -7.30 10.65 $ 
11.23 $ -5.14 $ -8.33 -5.42 $ -6.71 $ $ -2.42 $ 0.46 $ -2.39 -12.90 -11.33 -2.71 $ -0.58 -4.01 $ -8.10 $ $ -9.81 -10.49 5.71 -12.90 $ -2.01 -7.97 -7.07 -5.55 -0.65 -9.10 7.30 12.14 $ -1.23 $ $ $ -2.42 $ -14.94 -0.84 $ -6.97 $ 
$ -11.65 -8.04 -12.00 -14.07 4.00 -10.20 $ -6.01 $ -10.14 5.94 $ -4.87 $ -6.58 -11.58 -3.07 -13.94 $ 12.65 $ -0.58 $ -3.42 -11.39 $ 11.36 $ -7.17 $ -11.10 -4.58 7.84 $ -14.30 -12.23 10.04 $ -13.52 7.52 -12.65 5.07 $ -2.97 -2.26 $ $ -11.30 -12.23 
-1.04 $ -0.26 -4.07 -0.90 $ -10.46 -4.55 3.84 7.68 -12.00 $ $ -1.26 $ $ $ -8.46 -4.62 7.71 $ -11.55 $ -6.90 5.78 -10.36 -7.68 -0.14 -12.46 $ $ -13.84 11.87 -10.58 $ -11.52 0.01 -11.30 5.17 5.90 -1.90 -13.62 $ -2.97 -11.65 -6.87 $ -11.01 $ -10.52 
$ 6.52 2.81 -5.30 $ -8.90 -2.46 -14.62 $ 6.52 $ $ -2.87 $ $ -8.68 $ -5.62 -7.84 -7.90 -13.68 5.26 -2.52 -4.87 10.00 $ -4.97 $ $ $ 14.20 -8.58 $ $ $ $ $ -12.04 -2.71 -5.94 $ -3.30 -4.23 -1.01 2.90 -12.04 1.00 $ $ $ 
-10.87 $ -12.65 $ $ -5.52 11.58 -14.84 -2.42 -3.49 -8.90 -7.17 14.49 13.33 -13.62 -0.94 $ 6.23 $ -12.01 -8.14 $ 3.97 -5.30 7.62 -13.58 $ -0.01 -2.58 -5.87 -14.55 -0.52 -0.14 $ -9.58 4.42 $ -8.42 13.17 $ -9.52 -7.30 10.04 -12.71 -9.65 $ 0.30 -11.49 $ -3.62 
-4.97 -2.68 -0.74 -4.55 -7.78 -10.01 -3.65 $ -3.58 7.62 -5.58 $ -7.39 -1.97 -13.49 $ $ 9.84 -7.84 $ $ -11.71 -1.97 -12.30 $ $ -5.71 -8.14 $ -6.94 -0.62 $ 12.87 $ -12.14 -7.97 -3.97 -9.17 -3.58 $ $ $ -12.26 9.90 -2.14 -13.26 11.00 $ $ $ 
$ -2.97 -7.62 $ -11.55 -4.87 -11.14 7.01 -14.55 2.84 -10.49 $ -11.01 $ $ -0.74 -4.97 $ -2.68 -4.58 2.07 $ 8.30 -6.33 12.00 $ 7.42 -1.97 $ 9.81 -3.71 -12.46 $ -1.68 -8.71 4.87 $ -3.58 -7.49 $ -12.30 $ -2.94 -11.20 10.62 -10.00 $ $ -1.97 -10.68 
$ $ 11.04 $ -0.58 -4.23 -12.49 $ $ 4.52 5.65 13.10 -7.01 -9.36 $ -13.68 -5.58 0.81 -7.20 -2.42 -10.30 -8.36 -9.81 -2.84 12.65 $ 7.62 $ -11.23 3.39 -11.94 -14.04 -8.81 -0.07 -1.20 $ $ -4.71 7.33 $ -1.01 -2.26 $ -2.26 6.87 $ -8.23 -8.04 3.58 -11.30 
-9.49 -13.52 $ -10.62 10.30 -9.07 -3.87 -0.46 -6.97 -3.33 $ 14.87 $ $ $ $ $ -3.58 -12.39 -10.97 $ -10.14 -12.30 -0.62 -11.84 $ $ -1.20 -10.46 -13.78 -4.07 6.62 $ 7.81 $ -3.78 $ $ -0.42 $ $ $ -2.90 4.78 -10.97 -6.17 $ -8.65 9.42 -0.10 
$ 3.07 $ 7.84 $ -1.87 -6.74 10.01 $ $ $ $ -5.55 -5.90 14.46 -9.65 2.87 -11.30 -14.33 $ $ -1.87 4.65 11.58 $ 1.00 $ 10.84 $ 1.78 -7.74 -7.33 9.14 -3.30 $ -9.62 4.62 $ 8.36 7.62 $ $ -11.00 -2.74 -8.68 3.46 $ $ $ $ 
1.30 -3.49 -6.81 $ 6.33 -2.04 $ 7.39 -2.39 $ $ -9.07 $ $ $ -7.00 $ 2.81 12.94 $ 14.07 7.49 $ $ -4.97 $ $ -5.04 $ $ $ $ -11.07 $ @ $ 2.20 -7.30 $ -1.23 $ -0.97 2.90 4.81 $ -4.14 $ -4.58 8.23 $ 
-2.71 $ $ -13.84 $ $ 2.20 $ -4.62 -3.14 $ 1.23 8.17 -5.30 $ -8.68 -2.97 $ $ 11.33 $ $ $ $ -12.07 $ -3.90 -14.01 -1.26 $ -9.10 9.81 $ 4.84 4.26 10.36 -8.20 -14.07 -2.01 $ 6.94 -5.94 -2.39 $ 1.46 -3.04 -1.14 4.52 $ -12.33 
-6.39 -13.81 $ -9.52 -2.07 -14.68 -7.33 -5.55 9.23 $ -4.84 -7.94 -7.30 -12.01 -7.20 $ -13.68 1.55 $ $ $ -10.26 -12.94 -9.23 -11.30 -2.84 -13.39 14.10 $ $ -6.94 -7.68 4.46 $ 5.00 -5.49 -7.65 -2.30 $ $ 12.62 -7.78 $ $ 14.17 $ -10.17 -7.01 -6.62 5.78 
-6.87 -5.46 -13.01 -4.04 -5.26 8.81 2.07 -13.84 7.42 -5.26 $ -14.65 -0.23 -9.26 -3.14 $ $ -10.46 4.68 -10.97 $ -12.23 -12.65 2.33 $ -9.04 -9.97 $ -3.14 -3.23 0.52 -10.81 $ 12.36 -5.49 -6.00 $ $ 5.52 14.90 -11.74 $ $ -14.01 -6.81 -9.81 -10.17 $ 3.97 $ 
$ 10.33 -7.23 -14.97 $ 6.68 -5.58 -0.33 10.87 3.84 $ -10.87 $ -8.17 $ -14.14 $ $ -7.52 -12.71 $ -3.87 -5.68 1.33 $ -6.71 $ $ $ $ -4.14 -14.17 13.65 -2.84 -5.52 -3.46 -5.90 $ $ $ 9.14 -12.90 $ -11.68 -5.26 -0.97 $ -14.74 -5.52 11.55 
$ -9.39 $ $ -3.36 -11.04 $ $ 14.94 -1.00 -12.94 -4.65 -14.39 9.62 -7.55 5.07 $ -6.65 1.62 $ $ $ -7.71 -6.33 4.90 $ -12.33 6.52 $ -13.62 7.58 5.04 $ -12.20 $ 3.55 14.36 14.55 1.20 -12.23 -9.01 $ $ -5.87 $ -6.97 2.87 -9.94 -14.52 -14.97 
$ -1.39 12.36 $ -13.39 $ -5.90 14.39 $ -2.55 -1.04 1.78 -11.81 4.46 6.17 -6.87 6.90 10.87 -10.17 3.81 -9.84 -0.01 4.52 -4.94 -4.65 -6.71 1.55 -14.74 1.04 5.39 -0.94 -13.33 2.58 4.36 -6.36 8.14 -14.97 -11.68 -13.81 -5.00 -6.42 8.20 8.26 -8.20 -2.00 -0.81 7.33 -13.07 -1.68 9.17 
1.36 -0.17 11.17 -0.65 -4.49 -12.90 -9.39 10.55 -5.90 7.68 -8.00 5.30 9.49 12.04 -11.07 -4.68 11.52 -13.01 -9.00 6.71 -6.90 -12.78 -2.46 -8.33 -13.49 1.00 -7.81 9.33 0.01 -5.81 7.74 -10.46 -15.00 -10.78 13.07 -13.84 -2.58 6.46 8.42 14.81 0.81 -12.42 -6.04 -11.90 14.14 -5.14 -14.17 -10.10 -10.07 -6.14 
-7.33 13.17 -0.58 -1.94 5.39 0.94 0.49 0.81 -5.10 -0.62 -0.39 11.07 8.36 -13.74 -13.07 -12.62 10.87 -1.33 0.36 -5.42 4.97 -13.94 -4.71 14.00 13.39 -14.78 11.10 0.71 -12.07 -1.39 -2.74 -13.81 9.10 -13.36 6.58 -6.01 8.74 -4.20 7.55 -7.30 1.33 4.71 0.33 -14.74 -10.42 10.17 -9.68 9.71 -11.71 0.07 
0.39 8.78 -11.78 -4.68 8.81 1.71 -2.97 -10.78 -1.10 -6.39 -12.42 -3.26 7.97 0.58 7.33 -4.65 8.23 -6.87 -11.55 8.65 -5.04 12.78 -13.87 -11.55 0.33 -10.71 4.58 3.58 7.30 8.84 5.65 11.33 6.07 8.07 4.84 -1.49 -0.65 5.78 -8.46 -10.49 4.33 14.39 9.84 -0.07 -10.90 -5.55 -11.36 -4.01 -11.14 12.39 
2.94 1.68 -11.10 8.30 7.55 -7.30 -1.49 -8.58 3.26 5.33 -10.78 -12.14 -14.94 14.71 2.62 11.07 2.42 5.39 -10.84 2.46 -1.81 -1.10 -13.97 10.71 -6.39 1.39 12.90 9.30 0.68 6.87 -5.07 -10.81 -0.71 -8.04 0.90 2.68 -2.00 5.20 -2.68 -4.07 10.84 -0.58 -0.55 11.04 4.23 -0.62 11.10 -9.90 3.17 13.17 
5.30 6.97 9.78 -7.00 -5.62 -1.14 2.30 12.81 0.10 -5.36 1.00 5.23 -8.46 14.87 5.17 7.97 14.30 -5.46 11.74 14.87 -4.84 -11.00 4.71 -9.04 15.00 -9.62 -7.10 -8.74 -2.94 -8.42 -0.39 14.26 14.00 2.26 11.87 -4.33 11.46 -3.17 9.01 -14.26 -9.84 -14.17 13.20 -0.84 -0.01 10.62 -1.42 9.90 6.90 2.78 
-4.23 9.07 6.39 6.65 5.33 -14.07 14.36 -12.07 7.97 9.07 -1.46 12.49 -11.94 8.52 -6.14 -1.10 0.20 -0.81 -6.62 4.20 -8.90 2.42 1.58 -8.42 3.52 1.01 9.58 12.97 -6.90 -5.07 -10.90 -14.23 0.26 9.87 7.81 -3.30 -11.81 -12.71 -12.30 12.49 9.78 -12.68 -7.00 -12.07 -11.39 -0.87 -14.81 8.49 -10.71 -11.01 
-13.49 5.84 12.01 -7.49 3.68 0.52 3.49 -2.74 -7.71 -9.68 -14.36 2.71 -5.20 6.62 -14.46 -1.90 10.42 -7.14 -14.94 -3.62 0.74 -10.94 -3.04 0.65 -12.65 -3.20 -8.46 -13.39 -9.97 -4.10 -1.17 -9.00 9.17 -9.81 -1.65 -0.23 14.78 -11.33 -14.10 7.68 -2.74 -3.94 -13.23 -2.84 2.58 5.78 -10.97 0.65 0.20 2.87 
1.17 8.62 1.55 13.46 -3.10 2.23 -14.14 -13.20 2.23 -4.01 12.17 7.10 -11.42 -12.14 13.20 1.74 5.23 -14.71 6.81 6.30 -6.39 10.90 -10.00 -7.97 14.00 12.71 1.52 -5.17 -5.81 14.97 14.33 10.20 -3.84 -10.20 12.90 -5.68 8.10 0.90 14.87 -8.26 8.78 -8.74 11.52 12.04 -5.36 10.81 -7.04 6.20 4.04 6.94 
8.04 0.74 -0.58 8.55 -2.81 -1.07 -14.58 11.55 -10.36 6.55 -6.42 2.07 -10.20 -9.52 12.65 7.90 0.10 -0.36 -12.42 -4.68 -13.74 13.84 -2.55 7.42 3.97 -14.62 -0.33 11.90 -13.00 -12.81 7.81 1.33 2.71 12.78 -1.30 11.36 11.84 -12.62 1.10 10.17 10.10 2.46 -2.46 -11.84 -12.78 1.65 8.81 2.81 8.20 -10.07 
14.55 4.55 0.14 2.58 13.65 -3.36 5.33 7.58 -6.78 2.62 10.87 8.00 -1.81 0.10 -12.33 -5.49 -2.65 -7.23 13.17 6.04 9.58 -5.55 2.17 -8.68 -2.55 14.39 7.46 -4.30 -3.14 0.55 -6.81 4.00 -5.65 1.00 -12.81 11.20 -11.94 2.49 9.33 -1.87 4.42 -2.26 10.68 12.62 8.04 2.81 -1.97 -12.07 6.62 9.58 
10.55 8.78 5.20 -12.04 1.30 -10.30 4.26 -0.20 -4.04 11.94 11.81 -4.52 -5.33 -8.52 1.10 -1.33 9.90 4.14 -6.33 -9.65 10.90 6.39 2.55 -14.52 -2.26 -13.14 -2.10 -7.30 -4.39 7.81 7.58 -2.36 -11.62 10.01 -2.01 14.94 6.33 -9.55 -6.90 0.94 9.04 7.58 11.20 -11.33 5.07 -11.00 -7.20 8.17 -9.65 -13.65 
7.94 6.26 5.97 -13.94 13.71 1.33 2.78 13.71 7.20 1.36 14.90 11.84 12.00 1.71 11.01 6.94 13.94 3.20 1.14 13.71 3.10 4.74 4.17 6.23 6.04 14.10 1.33 0.39 8.87 3.36 14.94 7.14 11.52 13.07 14.81 2.90 4.36 7.42 9.14 0.07 6.74 3.00 7.87 5.74 13.68 7.00 13.90 5.10 1.10 8.78 
7.81 6.10 4.42 4.84 1.26 3.81 7.42 0.62 7.42 0.46 0.26 1.49 11.94 11.17 12.49 4.30 6.90 7.39 4.84 9.33 9.20 2.74 3.68 3.33 7.97 6.42 14.17 11.33 2.78 3.26 9.17 10.68 9.55 8.14 7.49 10.71 6.52 13.62 4.97 1.33 8.74 9.62 2.07 11.84 14.14 6.49 9.52 1.01 10.04 4.33 
2.30 14.49 2.81 6.87 8.71 12.87 13.23 7.30 12.78 3.23 0.39 1.00 14.81 4.49 6.33 5.62 14.01 1.17 6.97 12.52 14.17 4.78 5.81 13.94 5.74 7.65 6.58 4.26 5.17 10.49 2.52 2.26 11.52 8.36 0.33 6.26 2.65 7.00 14.52 5.26 7.30 0.07 14.01 7.84 2.97 12.26 8.62 0.58 9.17 0.04 
3.68 6.90 7.84 13.78 5.30 8.87 7.74 0.55 2.78 8.84 9.39 9.94 14.97 10.71 14.65 5.74 11.87 10.52 8.84 3.84 9.30 0.01 14.39 1.78 12.65 14.07 1.84 6.42 4.94 0.62 5.14 1.33 9.90 12.97 13.42 3.94 13.52 2.58 8.74 11.23 7.58 14.39 4.26 10.17 8.00 13.14 1.10 13.04 13.07 12.42 
4.68 12.39 8.74 2.39 5.52 6.65 8.14 6.10 11.23 7.00 1.07 12.17 5.23 2.20 12.00 2.20 6.74 10.30 10.90 14.52 8.42 3.23 6.20 1.58 13.65 12.46 14.68 4.97 4.87 8.23 8.74 1.52 12.04 0.94 10.52 10.36 6.62 6.55 9.97 1.26 1.68 8.33 8.36 5.23 5.42 14.07 11.90 8.97 0.58 9.97 
12.23 8.65 4.46 6.84 9.74 0.26 7.74 2.81 8.84 12.46 0.10 3.17 12.30 0.17 10.10 13.23 9.55 14.49 0.94 10.74 13.30 8.07 8.00 9.74 12.58 9.14 6.20 6.52 13.01 4.33 6.30 1.17 13.68 2.87 14.74 12.04 9.01 10.81 7.68 6.71 14.97 1.90 7.42 9.87 11.55 5.07 5.20 13.81 10.78 5.58 
13.33 12.14 1.58 1.46 12.74 5.94 9.04 8.52 14.04 0.23 6.39 10.74 8.52 11.00 10.01 4.26 0.52 1.23 14.01 6.17 2.39 1.20 13.42 9.23 5.87 8.17 0.55 13.42 11.20 0.01 12.78 6.90 2.87 8.71 5.55 9.01 4.78 3.14 0.87 4.97 2.20 4.94 4.90 14.81 11.74 8.33 6.07 7.81 8.33 12.81 
1.36 7.84 3.04 9.30 9.33 11.62 12.39 1.26 3.87 3.42 0.90 8.10 12.97 2.90 2.39 4.17 6.52 11.87 8.97 2.30 11.07 2.84 2.07 0.46 9.55 4.07 10.17 4.26 0.97 0.65 5.20 14.68 3.74 8.23 11.94 0.30 0.49 6.65 3.01 0.42 9.49 6.14 8.68 10.30 8.74 1.94 1.42 3.30 9.87 9.33 
13.00 9.04 2.46 0.81 10.84 14.14 1.01 0.10 9.17 3.87 10.62 2.84 11.46 8.71 7.36 1.49 14.87 2.10 5.94 6.97 14.84 9.20 3.97 12.97 6.58 4.26 7.62 3.04 9.97 7.55 13.87 11.87 13.17 4.94 2.07 10.20 5.62 7.62 13.30 4.39 1.39 11.65 0.01 11.58 3.39 10.23 5.42 1.23 5.97 9.71 

X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X 
Lives: 3
Score: 0.00
Bombs: 3

Enter bomb position (x,y): 22,8

Total uncovered score of 4.26 points
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X 
X X X X X X X - - - X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X 
X X X X X X X + $ $ X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X 
X X X X X X X + - $ X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X 
Lives: 3
Score: 4.26
Bombs: 2

Enter bomb position (x,y): 25,38
Bang!! Your bomb range is doubled

You have found the score double bonus tile! Your score for this roll has been doubled! If it was negative it has been made positive and doubled!
Total uncovered score of 803.17 points
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X - - - $ - + $ - + $ - - + - - $ + X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X - $ + $ - - - - - $ $ $ - + - - + X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X - - $ - - + $ - - $ - $ - - + - $ X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X - - - - - $ $ - + $ - - $ - + $ - X X X 
X X X X X X X - - - X X X X X X X X X X X X X X X X X X X X - + $ + $ - $ $ - $ $ $ - + - - $ X X X 
X X X X X X X + $ $ X X X X X X X X X X X X X X X X X X X X - - + - $ - + $ + + $ $ - - - + $ X X X 
X X X X X X X + - $ X X X X X X X X X X X X X X X X X X X X $ $ - $ @ $ + - $ - $ - + + $ - $ X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X - + $ + + + - - - $ + - - $ + - - X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X - - + $ + - - - $ $ + - $ $ + $ - X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X + - $ + - - $ $ + + - $ $ - - - - X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X - - + - - - - $ $ $ + - $ - - - $ X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X + + $ - $ + + + + - - $ $ - $ - + X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X - - + + - + - - - - - + + - - - + X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X + - - - + - - + + + + - - - + - - X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X - - + - + - + - + - + + + - - + - X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X + + + + + - - + - - + + + - - - - X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X - - - - + + - + - - + - - + + - + X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X 
Lives: 3
Score: 807.42
Bombs: 1

Enter bomb position (x,y): 10,45
Bang!! Your bomb range is doubled

Total uncovered score of -40.09 points
Your score has dipped below zero, you have lost a life :( 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X - - - X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X + - $ X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X - + - X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X - - - $ - + $ - + $ - - + - - $ + X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X - $ + $ - - - - - $ $ $ - + - - + X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X - - $ - - + $ - - $ - $ - - + - $ X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X - - - - - $ $ - + $ - - $ - + $ - X X X 
X X X X X X X - - - X X X X X X X X X X X X X X X X X X X X - + $ + $ - $ $ - $ $ $ - + - - $ X X X 
X X X X X X X + $ $ X X X X X X X X X X X X X X X X X X X X - - + - $ - + $ + + $ $ - - - + $ X X X 
X X X X X X X + - $ X X X X X X X X X X X X X X X X X X X X $ $ - $ @ $ + - $ - $ - + + $ - $ X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X - + $ + + + - - - $ + - - $ + - - X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X - - + $ + - - - $ $ + - $ $ + $ - X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X + - $ + - - $ $ + + - $ $ - - - - X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X - - + - - - - $ $ $ + - $ - - - $ X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X + + $ - $ + + + + - - $ $ - $ - + X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X - - + + - + - - - - - + + - - - + X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X + - - - + - - + + + + - - - + - - X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X - - + - + - + - + - + + + - - + - X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X + + + + + - - + - - + + + - - - - X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X - - - - + + - + - - + - - + + - + X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X 
Lives: 2
Score: 0.00
Bombs: 0
You've ran out of bombs or lives. Game Over!

*****Program Ends*****

]0;jeremy.kimotho@csa1:~/Desktop/CPSC_355/project_2jeremy.kimotho@csa1:~/Desktop/CPSC_355/project_2$ 
]0;jeremy.kimotho@csa1:~/Desktop/CPSC_355/project_2jeremy.kimotho@csa1:~/Desktop/CPSC_355/project_2$ exit
exit

Script done on 2020-12-09 17:42:14-07:00
